# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 10:05
from __future__ import unicode_literals

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import timezone_field.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_type', models.CharField(choices=[('Job Seeker', 'Job Seeker'), ('Company', 'Company')], default='Job Seeker', max_length=20, verbose_name='User Type')),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='User Image')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Last Name')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('accepting_terms', models.BooleanField(default=False, verbose_name='Terms & Condition')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super User')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_active', models.BooleanField(default=False, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name_plural': 'User',
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='AbstractUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='User Image')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('resume', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Completed', 'Completed')], default='Applied', max_length=20, verbose_name='Applied Job Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name_plural': 'Applied Jobs',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(choices=[('AM', 'AM'), ('USER', 'USER')], default='AM', max_length=20, verbose_name='Created By')),
            ],
            options={
                'verbose_name_plural': 'Area',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Last Name')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile Number')),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
                ('profession', models.CharField(choices=[('One Time Project', 'One Time Project'), ('On going Project', 'On going Project'), ('To be decided', 'To be decided')], default='One Time Project', max_length=50, verbose_name='Select Profession')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Last Name')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile Number')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(choices=[('AM', 'AM'), ('USER', 'USER')], default='AM', max_length=20, verbose_name='Created By')),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EducationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100, verbose_name='School Name')),
                ('degree', models.CharField(max_length=100, verbose_name='Degree Name')),
                ('field_of_study', models.CharField(max_length=100, verbose_name='Field of Study')),
                ('grade', models.CharField(max_length=100, verbose_name='Grade')),
                ('activities_socities', models.TextField(verbose_name='Activities and societies')),
                ('from_year', models.CharField(max_length=4, verbose_name='From Year')),
                ('to_year', models.CharField(max_length=4, verbose_name='To Year')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Education Details',
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('from_month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=15, verbose_name='From Month')),
                ('from_year', models.CharField(max_length=4, verbose_name='From Year')),
                ('to_month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=15, verbose_name='To Month')),
                ('to_year', models.CharField(max_length=4, verbose_name='To Year')),
                ('currently', models.BooleanField(default=False)),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Employment History',
            },
        ),
        migrations.CreateModel(
            name='FavouriteJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name_plural': 'Favourite Jobs',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(choices=[('AM', 'AM'), ('USER', 'USER')], default='AM', max_length=20, verbose_name='Created By')),
            ],
            options={
                'verbose_name_plural': 'Industry',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='JobManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=40)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('description', models.TextField()),
                ('duration', models.CharField(choices=[('0-3', '0-3'), ('3-6', '3-6'), ('6-12', '6-12'), ('12+', '12+')], default='0-3', max_length=10, verbose_name='Month')),
                ('type_of_project', models.CharField(choices=[('One Time Project', 'One Time Project'), ('On going Project', 'On going Project'), ('To be decided', 'To be decided')], default='One Time Project', max_length=50, verbose_name='What type of project you have?')),
                ('number_of_employees', models.IntegerField(default=0, verbose_name='How much employee you need?')),
                ('payment', models.CharField(choices=[('Pay by Hour', 'Pay by Hour'), ('Pay by Fixed Price', 'Pay by Fixed Price')], default='Pay by Hour', max_length=50, verbose_name='How would you like to pay?')),
                ('credit', models.CharField(choices=[('$10/HR', '$10/HR'), ('$20/HR', '$20/HR'), ('$30/HR', '$30/HR'), ('others', 'others')], default='$10/HR', max_length=30, verbose_name='Desired Salary')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('area', models.ManyToManyField(related_name='post_job_area', to='analyticsmaven.Area')),
            ],
            options={
                'verbose_name_plural': 'Job Management',
                'verbose_name': 'Job Details',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=40, null=True, verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(choices=[('AM', 'AM'), ('USER', 'USER')], default='AM', max_length=20, verbose_name='Created By')),
            ],
            options={
                'verbose_name_plural': 'Tools & Language',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserLanguageRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(default=0, max_length=1, verbose_name='Language Rate')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_rate', to='analyticsmaven.Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_language', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkillRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(default=0, max_length=1, verbose_name='Skill Rate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='analyticsmaven.Skills')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skill', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('abstractuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analyticsmaven.AbstractUser')),
                ('company_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Company Name')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('profile_completion', models.IntegerField(default=0)),
                ('industry', models.ManyToManyField(related_name='company_industry', to='analyticsmaven.Industry')),
                ('language', models.ManyToManyField(related_name='company_language', to='analyticsmaven.Language')),
                ('tools_and_language', models.ManyToManyField(related_name='company_tools_and_language', to='analyticsmaven.Skills')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company Management',
            },
            bases=('analyticsmaven.abstractuser',),
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('abstractuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analyticsmaven.AbstractUser')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Last Name')),
                ('experience_level', models.CharField(blank=True, choices=[('Expert', 'Expert'), ('Beginner', 'Beginner'), ('Average', 'Average')], max_length=30, null=True)),
                ('professional_title', models.CharField(default='', max_length=100, verbose_name='Professional Title')),
                ('overview', models.CharField(default='', max_length=100, verbose_name='Overview')),
                ('week_availability', models.CharField(blank=True, choices=[('4-8', '4-8 Hrs'), ('8-16', '8-16 Hrs'), ('16-30', '16-30 Hrs'), ('30-48', '30-48 Hrs')], max_length=10, null=True, verbose_name='Availability in Week')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal Code')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Nubmer')),
                ('timezone', timezone_field.fields.TimeZoneField(blank=True, null=True)),
                ('profile_completion', models.IntegerField(default=0)),
                ('area', models.ManyToManyField(related_name='job_seeker_area', to='analyticsmaven.Area')),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_education', to='analyticsmaven.Education')),
                ('industry', models.ManyToManyField(related_name='job_seeker_industry', to='analyticsmaven.Industry')),
                ('language_known', models.ManyToManyField(related_name='job_seeker_language', to='analyticsmaven.Language')),
                ('tools_and_language', models.ManyToManyField(related_name='job_seeker_tools_and_language', to='analyticsmaven.Skills')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Job Seeker Management',
            },
            bases=('analyticsmaven.abstractuser',),
        ),
        migrations.AddField(
            model_name='jobmanagement',
            name='language',
            field=models.ManyToManyField(related_name='post_job_language_jobmanagement', to='analyticsmaven.Language'),
        ),
        migrations.AddField(
            model_name='jobmanagement',
            name='tools_and_language',
            field=models.ManyToManyField(related_name='post_job_tools_and_language_jobmanagement', to='analyticsmaven.Skills'),
        ),
        migrations.AddField(
            model_name='favouritejobs',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_job', to='analyticsmaven.JobManagement'),
        ),
        migrations.AddField(
            model_name='favouritejobs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_job_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appliedjobs',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_job', to='analyticsmaven.JobManagement'),
        ),
        migrations.AddField(
            model_name='appliedjobs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobmanagement',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_name_jobmanagement', to='analyticsmaven.Company'),
        ),
        migrations.AddField(
            model_name='employment',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_employment', to='analyticsmaven.JobSeeker'),
        ),
        migrations.AddField(
            model_name='educationdetails',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_education', to='analyticsmaven.JobSeeker'),
        ),
    ]
