# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.FloatField(verbose_name='Analytics Mavens Fees')),
            ],
            options={
                'verbose_name_plural': 'Analytics Rate',
            },
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='analytics_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='rate'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='hourly_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Hourly Rate'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='paid_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='You will be paid'),
        ),
    ]
