# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0002_auto_20180726_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('id',), 'verbose_name_plural': 'Area'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ('id',), 'verbose_name_plural': 'Industry'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ('id',), 'verbose_name_plural': 'Tools & Language'},
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='timezone',
            field=models.CharField(blank=True, choices=[('Pacific Time', 'Pacific Time'), ('Mountain Standard Time', 'Mountain Standard Time'), ('Center Time', 'Center Time'), ('Eastern Time', 'Eastern Time')], max_length=10, null=True, verbose_name='Timezone'),
        ),
    ]
