# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0003_auto_20180731_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='timezone',
            field=models.CharField(blank=True, choices=[('Pacific Time', 'Pacific Time'), ('Mountain Standard Time', 'Mountain Standard Time'), ('Center Time', 'Center Time'), ('Eastern Time', 'Eastern Time')], max_length=50, null=True, verbose_name='Timezone'),
        ),
    ]
