# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0005_auto_20180731_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='experience_level',
            field=models.CharField(choices=[('Expert', 'Expert'), ('Beginner', 'Beginner'), ('Average', 'Average')], default='Beginner', max_length=30),
        ),
    ]
