# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0006_auto_20180731_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userskillrate',
            options={'ordering': ('-rate',), 'verbose_name_plural': 'Skill Rating'},
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='experience_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='Beginner', max_length=30),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Phone Nubmer'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Postal Code'),
        ),
    ]
