# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0009_chatlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlist',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='analyticsmaven.JobManagement'),
            preserve_default=False,
        ),
    ]
