# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0012_chatlist_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatlist',
            old_name='deleted',
            new_name='companydeleted',
        ),
        migrations.AddField(
            model_name='chatlist',
            name='jobseekerdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
