# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0013_auto_20180802_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatlist',
            options={'verbose_name_plural': 'Chat List'},
        ),
        migrations.AlterModelOptions(
            name='chats',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'Chats'},
        ),
        migrations.AlterField(
            model_name='employment',
            name='company',
            field=models.CharField(max_length=500, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='location',
            field=models.CharField(max_length=500, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='overview',
            field=models.CharField(default='', max_length=5000, verbose_name='Overview'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='professional_title',
            field=models.CharField(default='', max_length=500, verbose_name='Professional Title'),
        ),
    ]
