# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0014_auto_20180802_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='education',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
