# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0016_country_hours_timezone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timezone',
            options={'ordering': ('priority',), 'verbose_name_plural': 'Timezone'},
        ),
        migrations.AddField(
            model_name='timezone',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
