# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0017_auto_20180807_0527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hours',
            options={'ordering': ('id',), 'verbose_name_plural': 'Hours'},
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='country',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='week_availability',
        ),
    ]
