# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0022_chatlist_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='sign_up',
            field=models.CharField(choices=[('Analytics Maven', 'Analytics Maven'), ('Social', 'Social')], default='Analytics Maven', max_length=20, verbose_name='SignUp Type'),
        ),
    ]
