# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0023_myuser_sign_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='sign_up',
            field=models.CharField(choices=[('Analytics Maven', 'Analytics Maven'), ('linkedin-oauth2', 'linkedin-oauth2'), ('google-oauth2', 'google-oauth2'), ('facebook-oauth2', 'facebook-oauth2')], default='Analytics Maven', max_length=20, verbose_name='SignUp Type'),
        ),
    ]
