# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0026_auto_20180809_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='overview',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Overview'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='professional_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Professional Title'),
        ),
    ]
