# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 04:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0027_auto_20180809_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=2000, verbose_name='Message')),
                ('type', models.CharField(blank=True, choices=[('Applied Job', 'Applied Job'), ('Approved Job', 'Approved Job'), ('Completed Job', 'Completed Job'), ('Pending Job', 'Pending Job'), ('Chat', 'Chat')], max_length=20, null=True, verbose_name='Notification Type')),
                ('link', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Link')),
                ('seen', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificationreceiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificationsender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notifications List',
                'ordering': ('-created_at',),
            },
        ),
    ]
