# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0028_notificationlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Online'),
        ),
    ]
