# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0029_myuser_is_online'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsrate',
            options={'verbose_name_plural': "Analytic's Rate"},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('id',), 'verbose_name_plural': "Analytic's Area"},
        ),
        migrations.AlterModelOptions(
            name='chatlist',
            options={'ordering': ('-chatlist',), 'verbose_name_plural': 'Chat List'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',), 'verbose_name_plural': "Analytic's Countries"},
        ),
        migrations.AlterModelOptions(
            name='hours',
            options={'ordering': ('id',), 'verbose_name_plural': "Analytic's Hours"},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ('id',), 'verbose_name_plural': "Analytic's Industry"},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name_plural': "Analytic's Language"},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ('id',), 'verbose_name_plural': "Analytic's Tools & Language"},
        ),
        migrations.AlterModelOptions(
            name='timezone',
            options={'ordering': ('priority',), 'verbose_name_plural': "Analytic's Timezone"},
        ),
        migrations.AddField(
            model_name='language',
            name='created_by',
            field=models.CharField(choices=[('AM', 'AM'), ('USER', 'USER')], default='AM', max_length=20, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='language',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
