# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0030_auto_20180820_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmanagement',
            name='job_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobmanagement',
            name='number_of_employees',
            field=models.IntegerField(default=0, help_text='How much employee you need?', verbose_name='Employee Needed'),
        ),
    ]
