# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0031_auto_20180828_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjobs',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Approved', 'Approved'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='Applied', max_length=20, verbose_name='Applied Job Status'),
        ),
    ]
