# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0034_auto_20180829_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='incomplete_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlist',
            name='type',
            field=models.CharField(blank=True, choices=[('Applied Job', 'Applied Job'), ('Approved Job', 'Approved Job'), ('Completed Job', 'Completed Job'), ('Pending Job', 'Pending Job'), ('Closed Job', 'Closed Job'), ('Declined Job', 'Declined Job'), ('Chat', 'Chat')], max_length=20, null=True, verbose_name='Notification Type'),
        ),
    ]
