# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0035_auto_20180831_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobIncompletedReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name_plural': 'Applied Jobs',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.RemoveField(
            model_name='appliedjobs',
            name='incomplete_reason',
        ),
        migrations.AddField(
            model_name='jobincompletedreason',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_job_incomplete', to='analyticsmaven.AppliedJobs'),
        ),
    ]
