# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0036_auto_20180831_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='feeback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
