# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0037_appliedjobs_feeback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedjobs',
            old_name='feeback',
            new_name='feedback',
        ),
    ]
