# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0038_auto_20180831_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('first_name', models.CharField(max_length=40, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Last Name')),
                ('designation', models.CharField(max_length=100, verbose_name='First Name')),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile Number')),
                ('message', models.CharField(max_length=100, verbose_name='City and Country')),
            ],
            options={
                'verbose_name_plural': 'Board Members',
            },
        ),
    ]
