# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0039_boardmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmember',
            old_name='message',
            new_name='city_country',
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='User Email'),
        ),
    ]
