# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 12:49
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0040_auto_20180831_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Member Image'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='designation',
            field=models.CharField(max_length=100, verbose_name='Designation'),
        ),
    ]
