# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0041_auto_20180831_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(choices=[('AM', 'AM'), ('USER', 'USER')], default='AM', max_length=20, verbose_name='Created By')),
            ],
            options={
                'verbose_name_plural': "Analytic's Profession",
                'ordering': ('id',),
            },
        ),
    ]
