# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 13:15
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0042_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='resume',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='Resume'),
            preserve_default=False,
        ),
    ]
