# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 06:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0043_auto_20180831_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=2000, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_chat_list', to='analyticsmaven.ChatList')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagereceiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagesender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Message Notification',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='chats',
            name='read',
            field=models.BooleanField(default=True),
        ),
    ]
