# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0044_auto_20180903_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagenotification',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='messagenotification',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='messagenotification',
            name='sender',
        ),
        migrations.DeleteModel(
            name='MessageNotification',
        ),
    ]
