# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0045_auto_20180904_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlist',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_notification', to='analyticsmaven.JobManagement'),
            preserve_default=False,
        ),
    ]
