# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0046_notificationlist_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlist',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_notification', to='analyticsmaven.AppliedJobs'),
        ),
    ]
