# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0047_auto_20180904_0530'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appliedjobs',
            unique_together=set([('user', 'job')]),
        ),
    ]
