# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0049_transactionmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmanagement',
            name='key',
            field=models.CharField(default='', max_length=40, verbose_name='Paypal Transaction Key'),
            preserve_default=False,
        ),
    ]
