# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0051_transactionmanagement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Paypal Address'),
        ),
    ]
