# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 04:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0052_myuser_paypal_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('rate', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Review and Rating',
            },
        ),
        migrations.RemoveField(
            model_name='appliedjobs',
            name='feedback',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_job_rating', to='analyticsmaven.AppliedJobs'),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='jobseeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_job_seeker', to=settings.AUTH_USER_MODEL),
        ),
    ]
