# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 05:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0054_auto_20180906_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='company',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='jobseeker',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='reviewee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviewee', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='reviewer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
