# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0055_auto_20180906_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rating',
            field=models.CharField(blank=True, default='0', max_length=1, null=True, verbose_name='Company Rating'),
        ),
    ]
