# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0056_company_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
