# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0057_appliedjobs_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmanagement',
            name='payment',
            field=models.CharField(choices=[('ADVANCE', 'ADVANCE'), ('ESCROW', 'ESCROW')], default='ADVANCE', max_length=10, verbose_name='Payment Type'),
        ),
    ]
