# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0058_transactionmanagement_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmanagement',
            name='released',
            field=models.BooleanField(default=False, verbose_name='Payment Release'),
        ),
    ]
