# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-04 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0060_transactionmanagement_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='User Email'),
        ),
        migrations.AlterField(
            model_name='career',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='User Email'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='overview',
            field=models.TextField(blank=True, null=True, verbose_name='Overview'),
        ),
    ]
