# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0061_auto_20190204_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrer_profession', to='analyticsmaven.Profession'),
        ),
    ]
