# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0062_auto_20190325_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmanagement',
            name='credit',
            field=models.CharField(default='$10/HR', max_length=50, verbose_name='Desired Salary'),
        ),
    ]
