# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-29 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0063_auto_20190327_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='company_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='applied_company_name', to='analyticsmaven.Company'),
            preserve_default=False,
        ),
    ]
