# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-29 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0064_appliedjobs_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjobs',
            name='company_name',
        ),
    ]
