# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0065_remove_appliedjobs_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='to_month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=15, null=True, verbose_name='To Month'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='to_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='To Year'),
        ),
    ]
