# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0066_auto_20190503_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='to_month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='', max_length=15, verbose_name='To Month'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employment',
            name='to_year',
            field=models.CharField(default='', max_length=4, verbose_name='To Year'),
            preserve_default=False,
        ),
    ]
