# Generated by Django 2.2.3 on 2019-07-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsmaven', '0067_auto_20190503_0902'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatlist',
            unique_together={('company', 'jobseeker', 'job')},
        ),
    ]
