"""
Django settings for bluerobins project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/dashboard'
SOCIAL_AUTH_LOGIN_URL = '/dashboard'
SOCIAL_AUTH_LOGIN_ERROR_URL = '/dashboard'

SOCIAL_AUTH_FIELDS_STORED_IN_SESSION = ['user_type']

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "qn_x8rtrnjhs+s&1afdmkoblcpt-9n4l2_$7($y@m$h)9o)4sn"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'material.theme.lightblue',
    'material',
    'material.admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'timezone_field',
    'djrichtextfield',
    'django_countries',
    'captcha',
    'channels',
    'rest_framework',
    'templated_email',
    'social_django',
    'django_filters',
    'sslserver',

]

CUSTOM_APPS = [
    'analyticsmaven',
    'staticmanagement',
]


INSTALLED_APPS += CUSTOM_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware'
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'analyticsmaven.processors.admin_data',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'django.contrib.messages.context_processors.messages',
                'analyticsmaven.processors.skillSet',
                'analyticsmaven.processors.year_list',
                'analyticsmaven.processors.latestjob',
                'analyticsmaven.processors.favjobs',
                'analyticsmaven.processors.appliedjobs',
                'analyticsmaven.processors.hourlyrate',
                'analyticsmaven.processors.notification',
                # 'analyticsmaven.processors.user_experience_level',
            ],
        },
    },
]

WSGI_APPLICATION = 'bluerobins.wsgi.application'


SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.social_auth.associate_by_email',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'analyticsmaven.social.social',
)

AUTHENTICATION_BACKENDS = (
    'social_core.backends.open_id.OpenIdAuth',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.linkedin.LinkedinOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    'bluerobins.backends.CaseInsensitiveModelBackend',
)


# Databasepython manage.py make
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'bluerobindb',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': "13.250.224.209",
        'PORT': "5432"
    }
}
# 52.74.218.145
AUTH_USER_MODEL = "analyticsmaven.MyUser"
SECURE_SSL_REDIRECT = False
SOCIAL_AUTH_REDIRECT_IS_HTTPS = False
SOCIAL_AUTH_USER_MODEL = AUTH_USER_MODEL

SOCIAL_AUTH_FIELD_SELECTORS = ['email-address', ]


# Google Integration update - smriti
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = "767348907069-b42p34ckrifa2aiefr18e6hg" \
    "ikr3lklm.apps.googleusercontent.com"
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "7KvWORV_BLHD9wX-1OIkvJk_"


# Google Integration
# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = "761983307648-tm7mke6karuo61b1v51vfj69" \
#                                 "r7gguc33.apps.googleusercontent.com"
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "PL_8v-r96fHDO1ddlbfiHy8B"

# Linkedin Integration
SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = '86jxfbx6jd8tjz'
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = 'a9g588X4fmg9AcIG'

# SOCIAL_AUTH_LINKEDIN_SCOPE = ['r_basicprofile', 'r_emailaddress']
# LINKEDIN_EXTRA_FIELD_SELECTORS = [
#     'headline',
#     'public-profile-url',
#     'email-address',
#     'interests',
#     'skills',
# ]
# SOCIAL_AUTH_LINKEDIN_OAUTH2_EXTRA_DATA = [('id', 'id'), ('first-name', 'first_name'), ('last-name', 'last_name'), ('email', 'email_address'), ('positions', 'positions'), ('overview', 'summary'), ('professional_title', 'headline'), ('avatar', 'picture_url'),
#                                           ('site_standard_profile_request', 'site_standard_profile_request'), ('public-profile-url', 'public_profile_url'), ('country', 'location'), ('skills', 'skills')] + [
#     (field, field.replace('-', '_'), True)
#     for field in LINKEDIN_EXTRA_FIELD_SELECTORS]


SOCIAL_AUTH_LINKEDIN_OAUTH2_SCOPE = ['r_basicprofile', 'r_emailaddress', ]
# Add the fields so they will be requested from linkedin.

# Arrange to add the fields to UserSocialAuth.extra_data
SOCIAL_AUTH_LINKEDIN_OAUTH2_EXTRA_DATA = [
    ('id', 'id'),
    ('firstName', 'first_name'),
    ('lastName', 'last_name'),
    ('emailAddress', 'email_address'),
    ('headline', 'headline'),
    ('industry', 'industry'),
    ('summary', 'summary'),
    ('location', 'location'),
    ('positions', 'positions'),
    ('specialties', 'specialties')
]
SOCIAL_AUTH_LINKEDIN_OAUTH2_FIELD_SELECTORS = [
    'email-address', 'headline', 'industry', 'summary', 'location', 'positions', 'specialties'
]


SOCIAL_AUTH_FACEBOOK_KEY = "1020921821411118"
SOCIAL_AUTH_FACEBOOK_SECRET = "3b0a22421996b0468f2f87e7555f9e3c"
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id, name, email, age_range',
}
CLOUDINARY = {
    'cloud_name': 'mycloud6797',
    'api_key': '771624846989634',
    'api_secret': 'b7_UA-T0jZLQkEB_o2Rz2poHDN0',
    'secure': True,
}

SOCIAL_AUTH_URL_NAMESPACE = 'social'
AUTH_USER_MODEL = "analyticsmaven.MyUser"

LOGIN_URL = '/login'
LOGOUT_URL = '/logout'
LOGIN_ERROR_URL = '/'
LOGIN_REDIRECT_URL = '/dashboard'

DJRICHTEXTFIELD_CONFIG = {
    'js': ['//cdn.ckeditor.com/4.4.4/standard/ckeditor.js'],
    'init_template': 'djrichtextfield/init/ckeditor.js',
    'settings': {
        'width': 'auto',
        'height': 'auto'
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = "py-imtiyaz@mobiloitte.com"
EMAIL_HOST_PASSWORD = "@3864khanImtiyaz"
ESCROW_EMAIL = 'py-imtiyaz@mobiloitte.com'
ESCROW_KEY = '2512_rpk6usw57LzCpQlCUoGBJACMO91rpBwBZLFZ7Q0mkUQdq5HPnccwraD3eq4vbZLf'
# Use '' for top level template dir
TEMPLATED_EMAIL_TEMPLATE_DIR = 'templated_email/'
TEMPLATED_EMAIL_FILE_EXTENSION = 'email'

ROOT_URLCONF = 'bluerobins.urls'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
}
# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'asgi_redis.RedisChannelLayer',
        "LOCATION": "rediss://127.0.0.1:6379/1",
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],
        },
        'ROUTING': 'analyticsmaven.routing.routing',
    }
}
# ASGI_APPLICATION = 'bluerobins.asgi.channel_layer'

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

TIME_ZONE = "UTC"
LANGUAGE_CODE = "en-us"

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, "assets")
STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
