# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 13:39
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.CharField(blank=True, max_length=255, null=True, verbose_name='Analytics Maven Overview')),
                ('overview_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('mission_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('mission', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mission and Vision')),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='About Us')),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True, verbose_name='Question')),
                ('answer', models.CharField(blank=True, max_length=255, verbose_name='Answer')),
            ],
            options={
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='HowitWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'How it Works?',
                'verbose_name_plural': 'How it Works?',
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name_plural': 'Terms and Conditions',
            },
        ),
    ]
