# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticmanagement', '0003_faq_tagging'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Analytics Maven Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_description',
            field=models.TextField(default='', verbose_name='Title Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='mission',
            field=models.CharField(default='', max_length=200, verbose_name='Mission and Vision'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='mission_description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='overview',
            field=models.CharField(default='', max_length=200, verbose_name='Analytics Maven Overview'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='overview_description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
