# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 06:58
from __future__ import unicode_literals

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('staticmanagement', '0004_auto_20180831_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='mission_description',
            field=djrichtextfield.models.RichTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='overview_description',
            field=djrichtextfield.models.RichTextField(verbose_name='Description'),
        ),
    ]
