# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 09:27
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticmanagement', '0005_auto_20180831_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='avatar_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='About Us'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='banner_content',
            field=models.CharField(default='demo', max_length=500, verbose_name='Banner Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='banner_heading',
            field=models.CharField(default='demo heading', max_length=200, verbose_name='Banner Heading'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='About Us Banner'),
        ),
    ]
