# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 10:05
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticmanagement', '0006_auto_20181004_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='FAQ Banner'),
        ),
    ]
