# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticmanagement', '0007_faq_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='banner',
        ),
    ]
