# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 10:48
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticmanagement', '0008_remove_faq_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Banner')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name_plural': 'Privacy Policy',
            },
        ),
    ]
