# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 10:58
from __future__ import unicode_literals

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('staticmanagement', '0009_privacypolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=djrichtextfield.models.RichTextField(default='demo', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
