# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticmanagement', '0010_auto_20181004_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='banner_content',
            field=models.CharField(default='demo', max_length=500, verbose_name='Banner Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='banner_heading',
            field=models.CharField(default='demo', max_length=200, verbose_name='Banner Heading'),
            preserve_default=False,
        ),
    ]
