# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 11:19
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticmanagement', '0011_auto_20181004_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandconditions',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='banner_content',
            field=models.CharField(default='demo', max_length=500, verbose_name='Banner Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='banner_heading',
            field=models.CharField(default='demo', max_length=200, verbose_name='Banner Heading'),
            preserve_default=False,
        ),
    ]
