# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 11:28
from __future__ import unicode_literals

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('staticmanagement', '0012_auto_20181004_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howitworks',
            name='content',
            field=djrichtextfield.models.RichTextField(default='demo', verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='content',
            field=djrichtextfield.models.RichTextField(default='demo', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
