# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 07:39
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticmanagement', '0013_auto_20181004_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='howitworks',
            name='icon',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='Icon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='howitworks',
            name='title',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
