# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticmanagement', '0015_auto_20190325_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Refered Friend',
            },
        ),
    ]
