# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('staticmanagement', '0017_referfriend_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoAreWe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', djrichtextfield.models.RichTextField(verbose_name='Content')),
            ],
            options={
                'verbose_name_plural': 'Who Are We',
            },
        ),
    ]
