# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticmanagement', '0018_whoarewe'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoarewe',
            name='title',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
