# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-25 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticmanagement', '0019_whoarewe_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whoarewe',
            options={'verbose_name_plural': 'Who We Are'},
        ),
    ]
