# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticmanagement', '0020_auto_20190425_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whoarewe',
            options={'verbose_name_plural': 'Who we are'},
        ),
    ]
