# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-13 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticmanagement', '0021_auto_20190503_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'FAQ Tags'},
        ),
        migrations.AddField(
            model_name='referfriend',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
